// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-NRaEKGvDWGPTMvfz4duJcnD__BlYA0',
    appId: '1:696056396517:web:63ad437eed8d89b419720c',
    messagingSenderId: '696056396517',
    projectId: 'hazeupp-40d94',
    authDomain: 'hazeupp-40d94.firebaseapp.com',
    storageBucket: 'hazeupp-40d94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRWqd7whj64bYkTAq7oQEPg-xpEBkRk6U',
    appId: '1:696056396517:android:b2d39b266aac2a7f19720c',
    messagingSenderId: '696056396517',
    projectId: 'hazeupp-40d94',
    storageBucket: 'hazeupp-40d94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcx3Wf5GTFQ7_KMbETo2gxrEF2shjTU9M',
    appId: '1:696056396517:ios:7aa2747618f050fd19720c',
    messagingSenderId: '696056396517',
    projectId: 'hazeupp-40d94',
    storageBucket: 'hazeupp-40d94.appspot.com',
    androidClientId: '696056396517-4cus2umdkr45qofv7831reer5kp35re1.apps.googleusercontent.com',
    iosClientId: '696056396517-1tsl1m3hj78t1jme2jb11icn15le40o9.apps.googleusercontent.com',
    iosBundleId: 'com.example.hazeupp',
  );

}